### ISSUE TITLE
bug  

### ISSUE THREAD

**Issue by chriscp-cat** [boostorg/wave#132]
`` local codinglist = [[0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!="$&'()*+,-./<>?@[\]^_`{|}~]]``
This lua code will look like this if it is included
``local codinglist = [[01234567 89 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!="$&'()*+,-./<>?@[\]^_`{|}~]]``
I don't know why there are two more spaces

cmd:   --extended --c99 --preserve=2 --line=0

**Comment by jefftrull** [comment]
Hi! I'm not sure what this means. What command are you running and what does it have to do with Wave?

**Comment by chriscp-cat** [comment]
![image](https://user-images.githubusercontent.com/68489543/123861581-eefff280-d959-11eb-9636-410a873d4135.png)
![image](https://user-images.githubusercontent.com/68489543/123861705-10f97500-d95a-11eb-8cb3-d5f8ebd8f2d2.png)
[wave.zip](https://github.com/boostorg/wave/files/6736182/wave.zip)

**Comment by chriscp-cat** [comment]
There will be two more spaces

**Comment by jefftrull** [comment]
That's Wave, yes - but the input is not C++... I don't understand. Why are you trying to put Lua code through a C++ preprocessor?

**Comment by chriscp-cat** [comment]
I just want to include this file in another file And I think it should be a bug

**Comment by jefftrull** [comment]
I see - you want to run Wave as a Lua preprocessor, and it's doing something you think is wrong? Can you explain what is wrong?

I don't know what "There will be two more spaces" means.

**Comment by jefftrull** [comment]
For one thing, the input has an unterminated string - the double quote before `$&...` has no match

**Comment by chriscp-cat** [comment]
![image](https://user-images.githubusercontent.com/68489543/123862615-24f1a680-d95b-11eb-9cdd-115709b079e6.png)
![image](https://user-images.githubusercontent.com/68489543/123862639-2d49e180-d95b-11eb-8b57-3cd098154320.png)

**Comment by jefftrull** [comment]
Ah. In C++ numbers beginning with `0` are octal. So when it encounters `8` it decides that is a separate decimal number.

**Comment by jefftrull** [comment]
Then the following `A` begins a symbol, because `A` cannot be part of a decimal number.

**Comment by chriscp-cat** [comment]
So is this normal?

**Comment by jefftrull** [comment]
Nothing about your input is normal :) This is a C++ preprocessor, not a Lua preprocessor. So yes?

**Comment by chriscp-cat** [comment]
thinks

**Comment by chriscp-cat** [comment]
thanks
