### ISSUE TITLE
Is there multithreaded compilation support? 

### ISSUE THREAD

**Issue by w4454962** [boostorg/wave#139]
For example, it takes more than 1 minute to preprocess and compile a 10MB source file, which is really too slow

**Comment by jefftrull** [comment]
In my view performance has not been worked on very seriously in Wave - though @hkaiser will know better. "PRs welcome" as they say :)

I am curious about your phrasing, though - when you say "to preprocess _and compile_" what do you mean? Wave only does preprocessing.

**Comment by jefftrull** [comment]
You may be interested in the discussion on this old (pre-Github) ticket: https://svn.boost.org/trac10/ticket/1670

**Comment by w4454962** [comment]
Sorry, my wording is a little unclear. It refers to the time when the preprocessing macro is expanded

**Comment by hkaiser** [comment]
> You may be interested in the discussion on this old (pre-Github) ticket: https://svn.boost.org/trac10/ticket/1670

Thanks @jefftrull for digging this up. Indeed, setting `BOOST_WAVE_SUPPORT_THREADING=0` should help a lot.

**Comment by w4454962** [comment]
Thank you. The speed has been greatly improved after the modification.
