### ISSUE TITLE
Is there a way to add another directive that behaves as #include ?

### ISSUE THREAD

**Issue by malickf** [boostorg/wave#16]
I 'm trying to preprocess a file that has a C like language.
However the main difference is that it allows both #include or #import statement. 

ex :
#import <maximize.h>
**and**
#include <maximize.h>

They both behave in the standard way. 
I have tried to modify the custom_directive_hooks example without success : 

```
found_unknown_directive(ContextT const& ctx, ContainerT const& line, 
        ContainerT& pending)
    {
        namespace wave = boost::wave;

        typedef typename ContainerT::const_iterator iterator_type;
        iterator_type it = line.begin();
        wave::token_id id = wave::util::impl::skip_whitespace(it, line.end());

        if (id != wave::T_IDENTIFIER)
            return false;       // nothing we could do

        if ((*it).get_value() == "import" )
        {
             //-------------->  how to  map to "include" here ?
           std::copy(line.begin(), line.end(), std::back_inserter(pending));
            return true;
        }

        return false;           // unknown directive
    }
```
Could you help me with this ?

Many thanks, 

Malick

**Comment by hkaiser** [comment]
There is an example demonstrating how to add your own directives. See: https://github.com/boostorg/wave/tree/develop/samples/custom_directives.

**Comment by malickf** [comment]
Thanks but the library is very sophisticated, and the example is very simple with respect to the task I want to implement.. Should I call `on_include` within `found_unknown_directive` ? could you please make me a small example ?

**Comment by hkaiser** [comment]
> could you please make me a small example ?

I can try, but this might take a while before I get to it.

**Comment by malickf** [comment]
Thanks I'll try to continue to do it myself also but this seems very difficult to me (I have spent hours on this problem...). I just succeed to use the example to "skip" the #import statement.

**Comment by malickf** [comment]
Is there a way to call methods from the class https://github.com/boostorg/wave/blob/6a7af0e878c2eefa2a68535fdd729146893fdcc6/include/boost/wave/util/cpp_iterator.hpp#L235  inside https://github.com/boostorg/wave/blob/b23bad3a9944dd950e1b8fa7e06e052b06183cf3/samples/custom_directives/custom_directives.hpp#L35 ?
In hooks we usually gets `ContextT` but I don't know how to recover a pointer to the calling cpp_pointer . 
For instance how can I call .handle_pp_directive (https://github.com/boostorg/wave/blob/6a7af0e878c2eefa2a68535fdd729146893fdcc6/include/boost/wave/util/cpp_iterator.hpp#L1118) from inside the hook `found_unknown_directive`
Is this possible ?
Thanks

**Comment by hkaiser** [comment]
The ContextT gives you access to all of that. See https://github.com/boostorg/wave/blob/develop/include/boost/wave/cpp_context.hpp, this may help as well: https://github.com/boostorg/wave/blob/1980705a54f1ae334ffe43452404eeb93b08a0c4/include/boost/wave/cpp_context.hpp#L362-L365.

**Comment by malickf** [comment]
unfortunately It doesn't work, I cannot compile : asap I call `ctx.pop_iteration_context()`  from outside of the context, I get a lot of errors... I haven't been able to find a single line that call `pop_iteration_context()` from outside of the context .

**Comment by malickf** [comment]
Is there any chance someone can help me with this ? I have also recompiled `idl.re` by modifing somes lines to take into account the import keyword as below : 

```
 Pound PPSpace  ( "import" |"include") PPSpace "<" (any\[\n\r>])+ ">" 
        { BOOST_WAVE_RET(T_PP_HHEADER); }

    Pound PPSpace ( "import" |"include")  PPSpace "\"" (any\[\n\r"])+ "\"" 
        { BOOST_WAVE_RET(T_PP_QHEADER); } 

    Pound PPSpace ( "import" |"include")  PPSpace
        { BOOST_WAVE_RET(T_PP_INCLUDE); } 
```

I then obtained a new `idl_re.cpp` but at the end it still doesn't work. 
Thanks

**Comment by hkaiser** [comment]
I don't understand why this does not work. Note however, that there are two `.re` files, you might have to change both of them in order to be sure your modifications are picked up.

**Comment by malickf** [comment]
Ok thanks it may be my problem. I only applied my modif to a single .re file. 
However I don't know how to applied it to the second .re file. That is to say, to generate `cpp_re.cpp` and `cpp_re.inc` using re2ce from `cpp.re`. 

To get `idl_re.cpp` I used the following command  : 

`re2c.exe -o idl_re.cpp idl.re`

I can do the same with `cpp.re` but I won't have two files ( and the single file I get is quiet different of `cpp_re.cpp` )

Do you know the command line used to generate `cpp_re.cpp` and `cpp_re.inc` ?

**Comment by malickf** [comment]
Thanks ! I finally succeeded :-) You were right, I recompiled the second .re file and now it's working. Many thanks.
