### ISSUE TITLE
Non-standard escape sequences in string not supported

### ISSUE THREAD

**Issue by p8nut** [boostorg/wave#174]
During the parsing, it seem that Wave is not able to parse properly a string containing the escape character `\e`.
Using a slightly modified [quick_start exemple](https://www.boost.org/doc/libs/1_80_0/libs/wave/samples/quick_start/quick_start.cpp) you can reproduce the following output.
change the line 93 with `            std::cout << "["<< current_position <<"]" << (*first).get_value() << std::endl;` to display each line and token on a different line. 

the following C file produce 
`C file:`
```c
char *c = "test\n";
```
Output
```
[/tmp/./test.cpp:1:1]char
[/tmp/./test.cpp:1:5] 
[/tmp/./test.cpp:1:6]*
[/tmp/./test.cpp:1:7]c
[/tmp/./test.cpp:1:8] 
[/tmp/./test.cpp:1:9]=
[/tmp/./test.cpp:1:10] 
[/tmp/./test.cpp:1:11]"test\n"
[/tmp/./test.cpp:1:19];
[/tmp/./test.cpp:1:20]

[/tmp/./test.cpp:2:1]
```

the following C file produce 
`C file:`
```c
char *c = "test\e";
```
Output
```
[/tmp/test.cpp:1:1]char
[/tmp/test.cpp:1:5] 
[/tmp/test.cpp:1:6]*
[/tmp/test.cpp:1:7]c
[/tmp/test.cpp:1:8] 
[/tmp/test.cpp:1:9]=
[/tmp/test.cpp:1:10] 
[/tmp/test.cpp:1:11]"
[/tmp/test.cpp:1:12]test
[/tmp/test.cpp:1:16]\
[/tmp/test.cpp:1:17]e
[/tmp/test.cpp:1:18]"
[/tmp/test.cpp:1:19];
[/tmp/test.cpp:1:20]

[/tmp/test.cpp:2:1]
```

as you can see the `stringlit` is not detected anymore as the right type.

is there any solution to handle that right ?

**Comment by jefftrull** [comment]
It looks like `\e` is among the _conditionally supported_ escape sequences. For more see: https://cplusplus.github.io/CWG/issues/505.html

Is there a strong need for this feature?

**Comment by p8nut** [comment]
Yes I am currently working on a project that strongly need that feature.

My only other solution would be to escape the body before parsing by wave but seem to be a hacky solution and it won't fully fit my need.

**Comment by jefftrull** [comment]
Unfortunately those types of escape sequences are compiler-specific extensions. I suspect it would be a low priority (and require special code to enable/disable support) to go into mainline Wave.

If you are interested in implementing this yourself, I suggest changing the lexer definition [here](https://github.com/boostorg/wave/blob/44362764b92412a1d6b8b79ef293ebdcaa56579d/include/boost/wave/cpplexer/re2clex/cpp.re#L34). This file is input to a tool called [re2c](https://github.com/skvadrik/re2c/releases/tag/1.0.2);  you can use it to generate a new `cpp_re.inc` file in the same directory like this:

```
cd include/boost/wave/cpplexer/re2clex
re2c -b -o cpp_re.inc cpp.re
```

Then you can rebuild Wave and see if it works for you. Good luck!

**Comment by p8nut** [comment]
Thank you i'll take a look at it.
and keep you updated.

**Comment by jefftrull** [comment]
@hkaiser we could maybe put this in the "non-strict" lexer... any thoughts?

**Comment by p8nut** [comment]
I found some more information about the `\e` support in gcc [here](https://gcc.gnu.org/onlinedocs/gcc/Character-Escapes.html) and in clang [here](https://clang.llvm.org/doxygen/classclang_1_1StringLiteralParser.html#details)

At least i think it could be interesting that an error could be raise when an invalid character like an unknown escaped character is found.

or maybe the parser can process any printable character like gcc and clang do.

what do you think ?

**Comment by jefftrull** [comment]
Yeah, I'm not crazy about the "break up the string" result we currently have. Maybe an error would be better? Hopefully @hkaiser will weigh in.

I think, though, that `\e` is not the same as `e` - it produces an ESC character, if I understand correctly. So that would be special.

**Comment by jefftrull** [comment]
I retract that last comment. We just pass through the character and the backslash both when it's a valid control character.

@p8nut did you try making that change to Wave I suggested?

**Comment by hkaiser** [comment]
> It looks like `\e` is among the _conditionally supported_ escape sequences. For more see: https://cplusplus.github.io/CWG/issues/505.html
> 
> Is there a strong need for this feature?

I think just accepting the strings that contain those 'conditionally-supported' characters would be ok. At least clang does that without diagnostics. The current logic in Wave was implemented before CWG 505.

**Comment by p8nut** [comment]
Hello @jefftrull,

i try to change the escape `EscapeSequence` in the `cpp.re`, `strict_cpp.re`, `idl.re` where
```diff
diff --git a/include/boost/wave/cpplexer/re2clex/cpp.re b/include/boost/wave/cpplexer/re2clex/cpp.re
index 9839901..3567689 100644
--- a/include/boost/wave/cpplexer/re2clex/cpp.re
+++ b/include/boost/wave/cpplexer/re2clex/cpp.re
@@ -31,7 +31,7 @@ IntegerSuffix       = [uU] [lL]? | [lL] [uU]?;
 LongIntegerSuffix   = [uU] ("ll" | "LL") | ("ll" | "LL") [uU]?;
 MSLongIntegerSuffix = "u"? "i64";
 Backslash           = [\\] | "??/";
-EscapeSequence      = Backslash ([abfnrtv?'"] | Backslash | "x" HexDigit+ | OctalDigit OctalDigit? OctalDigit?);
+EscapeSequence      = Backslash ([\x20-\x7E] | Backslash | "x" HexDigit+ | OctalDigit OctalDigit? OctalDigit?);
 HexQuad             = HexDigit HexDigit HexDigit HexDigit;
 UniversalChar       = Backslash ("u" HexQuad | "U" HexQuad HexQuad);
 Newline             = "\r\n" | "\n" | "\r";
```

when i try with now it produce as expected the following output
```shell
[/tmp/./test.cpp:1:1]char
[/tmp/./test.cpp:1:5] 
[/tmp/./test.cpp:1:6]*
[/tmp/./test.cpp:1:7]c
[/tmp/./test.cpp:1:8] 
[/tmp/./test.cpp:1:9]=
[/tmp/./test.cpp:1:10] 
[/tmp/./test.cpp:1:11]"test\e"
[/tmp/./test.cpp:1:19];
[/tmp/./test.cpp:1:20]

[/tmp/./test.cpp:2:1]
```
this solution is a little bit more too inclusive and escape any printable character which is maybe not what we want...

**Comment by jefftrull** [comment]
@hkaiser are you comfortable with this? Also, should we distinguish in this case between the "strict" and non-strict lexers?

**Comment by hkaiser** [comment]
The standard says that (https://eel.is/c++draft/lex.ccon#nt:conditional-escape-sequence-char):
```
conditional-escape-sequence-char:
    any member of the basic character set that is not an octal-digit, a simple-escape-sequence-char, 
    or the characters N, o, u, U, or x
```
So I think we shouldn't use `[\x20-\x7E]` as a catch-all regex.

**Comment by p8nut** [comment]
ok it is possible to negate the regexp which look like that now
`[^\\01234567NouUx\x00-\x1F\x7F]`
which is based on the eel.is definition.

but with that definition if there is an incomplete definition it break again
```c
char * c = "test\N";
```
produce

```shell
[/tmp/test.cpp:1:1]char
[/tmp/test.cpp:1:5] 
[/tmp/test.cpp:1:6]*
[/tmp/test.cpp:1:7]c
[/tmp/test.cpp:1:8] 
[/tmp/test.cpp:1:9]=
[/tmp/test.cpp:1:10] 
[/tmp/test.cpp:1:11]"
[/tmp/test.cpp:1:12]test
[/tmp/test.cpp:1:16]\
[/tmp/test.cpp:1:17]N
[/tmp/test.cpp:1:18]"
[/tmp/test.cpp:1:19];
[/tmp/test.cpp:1:20]

[/tmp/test.cpp:2:1]
```

maybe the eager match could be an option or when we match a stringlit we could use the eager match because inside a string lit (i think) there is no need to process octal and or any other sequence

**Comment by hkaiser** [comment]
Frankly, I'm not sure why `\N` is not allowed. I'm not aware of any possibly conflicting escaped character sequence. We should conform to the Standard, however (there is usually reason to the madness ;-) ).

**Comment by p8nut** [comment]
My only point is that when we encounter a stringlit it should not break it apart because there is an escape character inside

**Comment by hkaiser** [comment]
> My only point is that when we encounter a stringlit it should not break it apart because there is an escape character inside

Should we report an error instead?

**Comment by p8nut** [comment]
for my project, the best solution would be to get the `stringlit` otherwise an exception could do.
(sorry for the long time to answer :-) )

**Comment by jefftrull** [comment]
`\N` is excluded because it begins a "named universal character escape", new in C++23.

Currently our approach to many invalid things is to report them as a sequence of simpler tokens instead, so breaking up a string literal in the face of an erroneous escape sequence seems OK to me.

I propose that we:

1. Implement _in the non-strict lexer_ support for conditional escape sequences as described in the standard - the "basic character set" minus all escape characters mentioned elsewhere (including N - since we currently don't support it there is no change there).
2. Implement this in the sample lexers also for consistency - that will be the bulk of the work, actually. For example, `slex` uses a Spirit Classic escape sequence parser, which we will need to fork.

@p8nut can you make progress with your fork? I think we will miss the 1.81 cutoff.

**Comment by jefftrull** [comment]
Upon reflection - and seeing what would need to change to support it - I decided to try support just `\e` and `\E`, which seem to be supported by both gcc and Clang. I couldn't find any others they both supported. Let me know what you think of the above PR and whether it would be enough. I think we could squeeze it in for 1.81.
