### ISSUE TITLE
Preserve code section

### ISSUE THREAD

**Issue by Zitrax** [boostorg/wave#224]
Does wave in any way support keeping a section of code unchanged, for example if I have:

```c++
#ifdef FOO
  #define BAR
#endif
```

and want to keep all that including the directives unevaluated. For example using a pragma around that specific block of code.

Or is it possible to implement something like that with the hooks?

**Comment by jefftrull** [comment]
I think the hooks are your go-to here... perhaps a combination of [found_directive](https://www.boost.org/doc/libs/1_85_0/libs/wave/doc/class_reference_ctxpolicy.html#found_directive), [evaluated_conditional_expression](https://www.boost.org/doc/libs/1_85_0/libs/wave/doc/class_reference_ctxpolicy.html#evaluated_conditional_expression), and [skipped_token](https://www.boost.org/doc/libs/1_85_0/libs/wave/doc/class_reference_ctxpolicy.html#skipped_token)? And if you need to define a custom pragma to turn this behavior on/off the [preprocess pragma output sample](https://github.com/boostorg/wave/tree/develop/samples/preprocess_pragma_output) may be of use.

**Comment by jefftrull** [comment]
If you have no further questions I may close this.

**Comment by Zitrax** [comment]
I think I will manage with what you said, thank you. I did some simplified testing that looked good. So I'll close it.
