### ISSUE TITLE
how to preserve comments ? 

### ISSUE THREAD

**Issue by malickf** [boostorg/wave#28]
Does anyone know how to preserve comments ? I saw some related code but can't figure out the way to get comments in the preprocessed file. 

I'm working with the waveidl sample.

I have tried to change this line : https://github.com/boostorg/wave/blob/6a7af0e878c2eefa2a68535fdd729146893fdcc6/samples/waveidl/idl.cpp#L375

to : 

`   output <<  (*first).get_value() << endl;`

but comment still doesn't appear. Only a new line is added.

Many thanks.

**Comment by hkaiser** [comment]
See the wave tool example for how to achieve this: https://github.com/boostorg/wave/blob/develop/tool/cpp.cpp#L914-L917

**Comment by malickf** [comment]
Many thanks, I have just added : 

`  ctx.set_language(
                boost::wave::enable_preserve_comments(ctx.get_language()));
			}`
and it effectively preserves comments . Great !

Thank you !

**Comment by hkaiser** [comment]
@malickf the wave tool is a nice resource exposing most of (If not all) capabilities of the library itself. You should be able to find many answers by looking at this code.
