### ISSUE TITLE
Implement __VA_OPT__ for C++20

### ISSUE THREAD

**Issue by hkaiser** [boostorg/wave#30]
C++20 will introduce `__VA_OPT__ (see: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0306r4.html), we should implement it in wave.

This shouldn't be difficult to implement as it's functionality is similar to `__VA_ARGS__`. The semantics are as follows: If the variable arguments contain no tokens, then `__VA_OPT__(content)` is replaced by no tokens (more precisely, by a placemarker). Otherwise, it is replaced by `content`, which can contain any admissible replacement text, including `__VA_ARGS__`.

As a side effect we'll need to introduce a new `language_support` option ` support_cpp2z` and a new configuration option `BOOST_WAVE_SUPPORT_CPP2Z`.

**Comment by mattcalabrese** [comment]
Recommend calling it 2A instead of 2Z (gcc and clang options for C++20 refer to it as c++2a).

**Comment by hkaiser** [comment]
@mattcalabrese Good point, thanks!

**Comment by eldiener** [comment]
Has this ever been implemented in Wave ? I am updating the Boost PP library with some support for detecting the __VA_OPT__ construct and a ffolproof test for emptiness using __VA_OPT__, and it would be nice to use the Wave driver, as I have so often done, to see what the expansion of macros using __VA_OPT__ should be like. I think this also needs a new Wave driver command line option, maybe something like '--c++20'. As always I am very appreciative of Wave for testing correct macro expansion.

**Comment by jefftrull** [comment]
@eldiener have a look at [my branch](https://github.com/jefftrull/wave/tree/feature/va-opt) - would love to have some feedback

**Comment by jefftrull** [comment]
I believe this is now fixed in develop but will keep it open in case others want to test or have other feedback prior to 1.74.

**Comment by jefftrull** [comment]
This has gone into master for 1.74.
