### ISSUE TITLE
wave sample - compiler error [C2955] with Visual Studio 2017

### ISSUE THREAD

**Issue by malickf** [boostorg/wave#43]
Compilation of the wave sample with Visual Studio 2017 (toolset msvc-14.1) fails with error code [C2955](https://docs.microsoft.com/fr-fr/cpp/error-messages/compiler-errors-2/compiler-error-c2955?view=vs-2019). It seems that since vs 2017, `we cannot use a class template or class generic as an identifier without a template or generic argument list`.

First error : 

 [`boost::wave::cpplexer::re2clex::Scanner`](https://github.com/boostorg/wave/blob/3d6ad95384bff8d074c211596bf9a3a7c4944f82/samples/waveidl/idllexer/idl_re.hpp#L27)  use of class template requires template argument list.

The `Scanner` is used multiples times without a template currently, for instance here:  https://github.com/boostorg/wave/blob/3d6ad95384bff8d074c211596bf9a3a7c4944f82/samples/waveidl/idllexer/idl_re.cpp#L73), 

I have tried to fix, unfortunately without success.

**Comment by hkaiser** [comment]
@malickf Thanks for reporting this. You're right we turned this class into a template a while back but apparently forgot to fix the example. @jefftrull, would that be something you could have a look at (I think you changed the Scanner to begin with)?

**Comment by jefftrull** [comment]
Ouch, sorry about that. I'll look into it this week. Will try to ensure the examples get built during CI too.

**Comment by jefftrull** [comment]
About 50% of the way through this but going on vacation :( Thanks for your patience.

I also found an issue with Filesystem usage - probably related to an API deprecation a few releases back. I could file a separate bug if desired.

You can follow my work here: https://github.com/jefftrull/wave/tree/bugfix/idl_sample_scanner

**Comment by jefftrull** [comment]
I built waveidl under VS2017 just now with the above changes; hopefully it will work for you too.

**Comment by malickf** [comment]
Thank you very much @jefftrull , I confirm that I can now correctly build the idl sample with Visual Studio 2017 (command:  `b2 toolset=msvc-14.1 link=static `) . Great !
