### ISSUE TITLE
Wave driver dies with undefined symbol at launch

### ISSUE THREAD

**Issue by jefftrull** [boostorg/wave#53]
Since sometime before 1.61 the "wave" driver, which is not built by default, dies when you launch it, complaining about not finding `defined_grammar_gen::parse_operator_defined(...)`. When I look carefully at what `libboost_wave.so` supplies vs. what wave expects I find the difference is the use of `std::mutex` in the library vs. `null_mutex` in the wave driver. Adding the following to `build/Jamfile.v2` in the project section seems to work around the problem:

```
      <define>BOOST_WAVE_SUPPORT_THREADING=0
```
which matches the definition in `tool/build/Jamfile.v2`. I couldn't say whether that was the "right" fix.

**Comment by hkaiser** [comment]
@jefftrull that is definitely the right fix as the driver does not use more than one thread, so no multi-threading issues could arise, thus it uses the `null_mutex` for the spirit parsers. Thanks for figuring that out!

**Comment by jefftrull** [comment]
@hkaiser just to be sure, using my workaround would mean that the Wave libraries themselves would be built with `null_mutex` and any users depending on them containing `std::mutex` would need to do their own builds... that OK?

**Comment by hkaiser** [comment]
@jefftrull alternatively you could rebuild the library just for the driver with threading disabled. 

OTOH, if we documented that the pre-built wave library is not thread-safe (which is what most people might prefer anyway as there is not really a point in using the same instance of the preprocessor concurrently from several threads), the solution you suggested is definitely viable.

**Comment by jefftrull** [comment]
I am now 70% sure this is a user error on my part. `libboost_wave.so` actually gets built twice, one for distribution (where `std::mutex` is used) and once for the purposes of the wave tool itself (null_mutex), with `RUNPATH` set appropriately. If you set `LD_LIBRARY_PATH` to the `stage/lib` directory you pick up the wrong one for the wave tool.

**Comment by jefftrull** [comment]
Concluding this is user error :)
