### ISSUE TITLE
Hooks not called for expanding specific predefined macros

### ISSUE THREAD

**Issue by jefftrull** [boostorg/wave#55]
This is a port of [TRAC 10733](https://svn.boost.org/trac10/ticket/10733) by @tberghammer. The original text reads:

>Non of the preprocessor hook is called during the expansion of the following predefined macros: `__LINE__`, `__FILE__`, `__INCLUDE_LEVEL__`.
>
>This is because the expansion of these macros are handled with a specific code path which skips the hooks.
>
>Expected behavior:
>
>- expanding_object_like_macro hook is called before the expansion
>- expansion happens based on the return value from the hook
>- expanded_macro hook is called after the expansion

**Comment by jefftrull** [comment]
I verified this issue still exists by using the attached testcase.
[trac10733.cpp](https://github.com/boostorg/wave/files/4050196/trac10733.cpp.txt)
.

**Comment by jefftrull** [comment]
I wonder if `__VA_OPT__()` should be traced also

**Comment by hkaiser** [comment]
> I wonder if __VA_OPT__() should be traced also

Would we have to trace `__VA_ARGS__` in this case as well? What other macros need to be handled?

**Comment by jefftrull** [comment]
@hkaiser for `__VA_ARGS__` what does it mean to "rescan"? I can understand when to call `expanding_macro` and `expanded_macro` but currently rescanning only happens for the parent variadic macro. Should we contrive to call the rescan hook anyway, somehow?

**Comment by hkaiser** [comment]
> @hkaiser for __VA_ARGS__ what does it mean to "rescan"? I can understand when to call expanding_macro and expanded_macro but currently rescanning only happens for the parent variadic macro. Should we contrive to call the rescan hook anyway, somehow?

@jefftrull I think that the only difference between a 'normal' argument of a function-like macro and `__VA_ARGS__` is that the latter refers to the overall token sequence represented by all parameters that are matched by the ellipses. All parameters that match the ellipses are expanded before being inserted into the replacement list in the same way as any parameter matching a non-variadic argument is expanded and inserted into the replacement list. Rescanning is nothing specific to `__VA_ARGS__` as it affects the replacement list after all arguments have been handled. 

In this sense `__VA_ARGS__` is not a macro on it's own, it is a predefined name that refers to all parameters matched by the ellipses of a variadic function-like macro.

**Comment by jefftrull** [comment]
OK! But what should we do with it, then...? Skip the rescan hook? Skip all the hooks? I'm not sure how to proceed.

**Comment by hkaiser** [comment]
Let's not treat `__VA_ARGS__` as a macro to begin with. We're not treating any parameter of a function-like macro as a macro itself (i.e. in `#define FOO(x) x`, `x` is not treated as a macro either).

**Comment by jefftrull** [comment]
OK! How do you feel about `__VA_OPT__`? We could call function-like macro hooks there...

**Comment by hkaiser** [comment]
> OK! How do you feel about __VA_OPT__? We could call function-like macro hooks there...

Yes, `__VA_OPT__()` is explicitly defined as a function-like macro. We could call the hooks for it.
